"""cmcc 2

Revision ID: 33cdc48a7e52
Revises: 9b1c11e42cc8
Create Date: 2018-05-08 15:37:49.069110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cdc48a7e52'
down_revision = '9b1c11e42cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectname', sa.String(length=140), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('GeneralProject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['GeneralProject_id'], ['general_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=140), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_item')
    op.drop_table('project')
    # ### end Alembic commands ###
